version: '3.1'

services:

  stats-server:
    build: ewm-stat/stat-server/
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin


  stats-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  # ewm-service:
  #  ports:
  #    - "8080:8080"

  # ewm-db:
  #  image: postgres:14-alpine
