create table if not exists endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    ip VARCHAR(31) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL
);
